"""updated new ActivityDestination table for connection between Activity and Destination tables

Revision ID: 1a706a37890b
Revises: 4ccb5b2da701
Create Date: 2024-07-17 21:00:49.536526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a706a37890b'
down_revision = '4ccb5b2da701'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_destinations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('destination_id', sa.Integer(), nullable=True),
    sa.Column('activity_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], name=op.f('fk_activity_destinations_activity_id_activities')),
    sa.ForeignKeyConstraint(['destination_id'], ['destinations.id'], name=op.f('fk_activity_destinations_destination_id_destinations')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activity_destinations')
    # ### end Alembic commands ###
